apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-tasks-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ChetanLaxane873/argo-helm.git
    targetRevision: HEAD
    path: helm-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: tasks-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true