apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tasksapp-ns
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: {{.Values.database.containers.image}}
          ports:
            - containerPort: {{.Values.database.containers.ports.containerport}}
          volumeMounts:
            - name: {{.Values.database.containers.volumemounts.name}}
              mountPath: {{.Values.database.containers.volumemounts.mountpath}}
      volumes:
        - name: {{.Values.database.volumes.name}}
          persistentVolumeClaim:
            claimName: {{.Values.database.volumes.persistentvolumeclaim.claimname}}