apiVersion: v1
kind: Service
metadata:
  namespace: tasksapp-ns
  name: tasksapp-svc
spec:
  selector:
    app: tasksapp
  ports:
    - port: {{.Values.appsvc.ports.port}}
      targetPort: {{.Values.appsvc.ports.targetport}}
  type: {{.Values.appsvc.type}}